nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/check-node-version.cjs
    # https://github.com/yarnpkg/berry/issues/1177#issuecomment-911833338
    spec: "https://raw.githubusercontent.com/Akryum/yarn-check-node/main/bundle/check-node-version.js"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
